### ISSUE TITLE
Analysis code

### ISSUE THREAD

**Issue by seabbs** [EmilieFinch/covid-reinfection#1]
Great job on the repository and congrats for having a clear readme. 

Ideally, it would be great to include the code used to develop the analysis as well as the code used to generate the figures. Even if the data is confidential there shouldn't be any problem sharing it and it's really required to validate the work.

**Comment by EmilieFinch** [comment]
Thanks! Yep good point, I'll definitely keep this in mind for the future. Here the code generating the odds ratios for the main analysis is very similar to the code presented for the simulation (except that a logistic regression is run within the for loop instead of the risk ratio calculation).
