### ISSUE TITLE
RM at top of code + install packages

### ISSUE THREAD

**Issue by seabbs** [EmilieFinch/covid-reinfection#2]
Very minor style comments so just close this once read (and slack me if interested in more detail). 

It's generally not considered great practise to use the rm set up at the top of scripts. I can link to some blogs which get intense about it if interested. 

Really good to see some install instructions but a couple of points.

-  If all packages from cran having a list of install packages is a little redundant. You could just let please install from cran as a default and list any other installs from elsewhere. There are other options here like pacman, using a description file, or renv that might be of interest as they capture the version/provide install mechanisms. 

-  if interested in making your code reproducible it's best to avoid depending on the tidyverse as this is forcing people to install 60 packages. Just load the ones your using or adjust when wrapping up the analysis.  

Otherwise really nice stuff. If you haven't already checked it out i'd have a look at the purrr package as that might help make sone of the for loops a little more concise.

**Comment by EmilieFinch** [comment]
Thank you for the suggestions!
