### ISSUE TITLE
Change simulation risk

### ISSUE THREAD

**Issue by seabbs** [EmilieFinch/covid-reinfection#3]
Is the code present for the analyses you did looking at different risk curves (aside from the twin peaks presented in your appendix)? From reading through its looks like this is read in after presumably being generated elsewhere?

**Comment by EmilieFinch** [comment]
I've included the code for the simulation presented in the appendix of the paper (which uses a risk distribution based on the PCR testing data in the cohort to more closely mirror the main analysis). But other versions we ran were exactly the same just with other hypothetical distributions put into `dist`.

**Comment by seabbs** [comment]
It would be nice to include those sort of steps  in the code for future work
